apply plugin: 'maven-publish'
apply plugin: 'org.jetbrains.dokka'

// Only run when NOT on JitPack
if (System.getenv("JITPACK") == "true") {
    logger.lifecycle("Running on JitPack – skipping signing tasks")
} else {
    apply plugin: 'signing'
}

tasks.register('androidSourcesJar', Jar) {
    archiveClassifier.set('sources')
    if (project.plugins.findPlugin("com.android.library")) {
        from android.sourceSets.main.java.srcDirs
        from android.sourceSets.main.kotlin.srcDirs
    } else {
        from sourceSets.main.java.srcDirs
        from sourceSets.main.kotlin.srcDirs
    }
}

tasks.register('javadocJar', Jar) {
    dependsOn dokkaJavadoc
    archiveClassifier.set('javadoc')
    from dokkaJavadoc.outputDirectory
}

artifacts {
    archives androidSourcesJar
}

group = 'com.github.Javi-space'
version = "0.10.0-ppwas"

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                artifactId = 'libaums'
                version = "0.10.0-ppwas"

                if (project.plugins.findPlugin("com.android.library")) {
                    from components.findByName("android") ?: components.findByName("release")
                } else {
                    from components.java
                }

                artifact androidSourcesJar
                artifact javadocJar

                pom {
                    name = 'libaums'
                    description = 'Android USB mass storage library with FAT32 support.'
                    url = 'https://github.com/Javi-space/libaums'
                    licenses {
                        license {
                            name = 'The Apache Software License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }
                    developers {
                        developer {
                            id = 'Javi-space'
                            name = 'Javi-space'
                            email = 'technologiescontrol@gmail.com'
                        }
                        developer {
                            id = 'magnusja'
                            name = 'Magnus Jahnen'
                            email = 'github@mgns.tech'
                        }
                        developer {
                            id = 'depau'
                            name = 'Davide Depau'
                            email = 'davide@depau.eu'
                        }
                    }
                    scm {
                        connection = 'scm:git:https://github.com/Javi-space/libaums.git'
                        developerConnection = 'scm:git:https://github.com/Javi-space/libaums.git'
                        url = 'https://github.com/Javi-space/libaums'
                    }
                }
            }
        }
    }
}


/*
apply plugin: 'maven-publish'
apply plugin: 'signing'
apply plugin: 'org.jetbrains.dokka'

// Skip publishing/signing when running on JitPack
if (System.getenv("JITPACK") == "true") {
    logger.lifecycle("Running on JitPack – skipping signing/publishing tasks")
    return
}

tasks.register('androidSourcesJar', Jar) {
    archiveClassifier.set('sources')
    if (project.plugins.findPlugin("com.android.library")) {
        // For Android libraries
        from android.sourceSets.main.java.srcDirs
        from android.sourceSets.main.kotlin.srcDirs
    } else {
        // For pure Kotlin libraries, in case you have them
        from sourceSets.main.java.srcDirs
        from sourceSets.main.kotlin.srcDirs
    }
}

tasks.withType(dokkaHtmlPartial.getClass()).configureEach {
    pluginsMapConfiguration.set(
            ["org.jetbrains.dokka.base.DokkaBase": """{ "separateInheritedMembers": true}"""]
    )
}

tasks.register('javadocJar', Jar) {
    dependsOn dokkaJavadoc
    archiveClassifier.set('javadoc')
    from dokkaJavadoc.outputDirectory
}

artifacts {
    archives androidSourcesJar
}

group = 'com.github.Javi-space'
version = "0.10.0-pwas"


afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
//                from components.release
                // The coordinates of the library, being set from variables that
                // we'll set up later
//                groupId PUBLISH_GROUP_ID
//                artifactId PUBLISH_ARTIFACT_ID
//                version PUBLISH_VERSION

//                groupId = 'com.github.Javi-space'
                artifactId = 'libaums'
//                artifactId PUBLISH_ARTIFACT_ID
                version = "0.10.0-pwas"

                // Two artifacts, the `aar` (or `jar`) and the sources
                if (project.plugins.findPlugin("com.android.library")) {
                    from components.findByName("android") ?: components.findByName("release")
                } else {
                    from components.java
                }

                artifact androidSourcesJar
                artifact javadocJar

              // Mostly self-explanatory metadata
              pom {
//                    name = PUBLISH_ARTIFACT_ID
                  name = 'libaums'
                    description = 'Android USB mass storage library with FAT32 support.'
                    url = 'https://github.com/Javi-space/libaums'
                  licenses {
                        license {
                            name = 'The Apache Software License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }

                    developers {

                        developer {
                            id = 'Javi-space'
                            name = 'Javi-space'
                            email = 'technologiescontrol@gmail.com'
                        }

                        developer {
                          id = 'magnusja'
                          name = 'Magnus Jahnen'
                          email = 'github@mgns.tech'
                        }
                        developer {
                          id = 'depau'
                          name = 'Davide Depau'
                          email = 'davide@depau.eu'
                        }

                        // TODO add all the others
                    }

                // Version control info - if you're using GitHub, follow the
                // format as seen here
                scm {
                        connection = 'https://github.com/Javi-space/libaums.git'
                        developerConnection = 'https://github.com/Javi-space/libaums.git'
                        url = 'https://github.com/Javi-space/libaums'
                    }
                }
            }
        }
    }
}

//signing {
//    useInMemoryPgpKeys(
//            rootProject.ext["signing.key"],
//            rootProject.ext["signing.password"],
//    )
//    sign publishing.publications
//}*/
